#!/bin/bash

fullJSLastModified=$(date -r abbreviation-autocomplete.js +%s)
minifiedJSLastModified=$(date -r abbreviation-autocomplete.min.js +%s)

if [ $fullJSLastModified -gt $minifiedJSLastModified ]; then
  echo "ERROR: minified version is not up to date"
  exit 1
fi
